version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  mailcatcher:
    image: instructure/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
      - 8080:8080
    expose:
      - 8080
